### ISSUE TITLE
Двойной вход в лобби

### ISSUE THREAD

**Issue by ed-asriyan** [lieroz/joking-hazard-02-2017#1]
Пользователь может зайти в лобби, если он уже состоит в каком-нибудь лобби или игре.

**Comment by wolf1996** [comment]
Пофиксил для лобби

**Comment by wolf1996** [comment]
Добавил проверку по игре. Тестируйте

**Comment by ed-asriyan** [comment]
1. Создаю первый соединение A к /lobby
2. Создаю второй соединение B к /lobby
**3. На B приходит информация, что в лобби два меня**
4. Разрываю соединение A
**5. Разрыв или ошибка (попозже могу сказать точно) на соединении B**
